repos:
- repo: local
  hooks:
  - id: refactoring
    name: refactoring
    language: system
    entry: ruff
    args: ["check", ".", "--config", "pyproject.toml", "--fix"]
    types: [python]
  - id: pyright
    name: pyright
    language: system
    entry: pyright
    types: [python]